kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: esyfo-kafka-manager
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2025.06.17-12.54-36e7798
  ingresses:
    - https://esyfo-kafka-manager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 0
    max: 0 # Max 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1m
      memory: 256Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 1fac48f0-9744-4d44-a5b5-e2c8aa2ca42b # team-esyfo
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [ 
            {
              "name": "team-esyfo.varselbus",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
